all: leer_bd, escribir_bd, leer, borrar

leer_bd: GestionCO2_Ficheros.py
	python GestionCO2_Ficheros.py db.sqlite3

escribir_bd: GestionCO2_Ficheros2.py
	python GestionCO2_Ficheros2.py db.sqlite3

borar_bd: borrar_BD.py
	python borrar_BD.py db.sqlite3

leer: leer.py
	python leer.py db.sqlite3

