# Generated by Django 3.0rc1 on 2019-11-18 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Agua, Electricidad, Aceite, Propano, Gas Natural, Gasolina o Diesel', max_length=50, verbose_name='¿Que ha consumido?')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(verbose_name='Fecha del consumo')),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacion', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha contratacion')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(verbose_name='Fecha contratacion')),
                ('empresa', models.ManyToManyField(to='GestionCO2.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField(verbose_name='KM recorridos')),
                ('transporte', models.CharField(max_length=50)),
                ('noches_hotel', models.IntegerField(verbose_name='Noches en hotel')),
                ('personal', models.ManyToManyField(to='GestionCO2.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('fecha', models.DateField(verbose_name='Fecha compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medios', models.CharField(help_text='Paneles Solares o Molinos eolicos', max_length=50, verbose_name='Tipo de Generador')),
                ('cantidad', models.IntegerField(help_text='en KWH')),
                ('fecha', models.DateField(verbose_name='Fecha de la generacion')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Edificio')),
            ],
        ),
        migrations.AddField(
            model_name='edificio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa'),
        ),
        migrations.CreateModel(
            name='VehiculoConsumo',
            fields=[
                ('consumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionCO2.Consumo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Personal')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Vehiculo')),
            ],
            bases=('GestionCO2.consumo',),
        ),
        migrations.CreateModel(
            name='EdificioConsumo',
            fields=[
                ('consumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionCO2.Consumo')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Edificio')),
            ],
            bases=('GestionCO2.consumo',),
        ),
    ]
