# Generated by Django 3.0rc1 on 2019-11-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=30)),
                ('localizacion', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha contratacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa')),
            ],
        ),
    ]
