# Generated by Django 3.0rc1 on 2019-11-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
