# Generated by Django 3.0rc1 on 2019-11-18 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0002_auto_20191118_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripcion'),
        ),
    ]
