# Generated by Django 3.0rc1 on 2019-11-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0002_edificio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medios', models.CharField(choices=[(1, 'Paneles Solares'), (2, 'Molinos eolicos'), (3, 'Otros...')], max_length=50, verbose_name='Tipo de Generador')),
                ('cantidad_generada', models.IntegerField(help_text='en KWH')),
                ('fecha_generacion', models.DateField(verbose_name='Fecha de la generacion')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Edificio')),
            ],
        ),
    ]
