# Generated by Django 3.0rc1 on 2019-11-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0003_auto_20191118_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='empresa',
        ),
        migrations.AddField(
            model_name='edificio',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa'),
        ),
    ]
