# Generated by Django 3.0rc1 on 2019-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0003_generador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha contratación'),
        ),
        migrations.AlterField(
            model_name='generador',
            name='fecha_generacion',
            field=models.DateField(verbose_name='Fecha de la generación'),
        ),
        migrations.AlterField(
            model_name='generador',
            name='medios',
            field=models.CharField(choices=[('1', 'Paneles Solares'), ('2', 'Molinos Eólicos'), ('3', 'Otros...')], max_length=50, verbose_name='Tipo de Generador'),
        ),
    ]
