# Generated by Django 3.0rc1 on 2019-11-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0004_auto_20191122_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tranporte', models.CharField(choices=[('1', 'Coche'), ('2', 'Moto'), ('3', 'Autobus'), ('4', 'Camión')], max_length=50, verbose_name='Vehiculo')),
                ('matricula', models.CharField(max_length=8)),
                ('tamano', models.CharField(choices=[('1', 'Pequeño'), ('2', 'Mediano'), ('3', 'Grande')], max_length=50, verbose_name='Tamaño')),
                ('fecha_compra', models.DateField(verbose_name='Fecha compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa')),
            ],
        ),
    ]
