# Generated by Django 3.0rc1 on 2019-11-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0005_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellidos_persona', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha contratacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa')),
            ],
        ),
    ]
