# Generated by Django 3.0rc1 on 2019-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0005_auto_20191118_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='empresa',
        ),
        migrations.AddField(
            model_name='edificio',
            name='empresa',
            field=models.ManyToManyField(to='GestionCO2.Empresa'),
        ),
    ]
