# Generated by Django 3.0rc1 on 2019-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0006_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(verbose_name='KM recorridos')),
                ('transporte', models.CharField(choices=[('1', 'Coche'), ('2', 'Avión'), ('3', 'Autobus'), ('4', 'Tren'), ('5', 'Barco')], max_length=50)),
                ('noches_hotel', models.IntegerField(verbose_name='Noches en hotel')),
                ('personal', models.ManyToManyField(to='GestionCO2.Personal')),
            ],
        ),
    ]
