# Generated by Django 3.0rc1 on 2019-11-22 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0007_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='noches_hotel',
            field=models.IntegerField(default=0, verbose_name='Noches en hotel'),
        ),
    ]
