# Generated by Django 3.0rc1 on 2019-11-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0008_auto_20191122_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.IntegerField()),
                ('fecha_consumo', models.DateField(verbose_name='Fecha del consumo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoConsumo',
            fields=[
                ('consumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionCO2.Consumo')),
                ('tipo', models.CharField(choices=[(1, 'Electricidad'), (2, 'Gasolina'), (3, 'Diesel')], max_length=50, verbose_name='¿Que ha consumido?')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Personal')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Vehiculo')),
            ],
            bases=('GestionCO2.consumo',),
        ),
        migrations.CreateModel(
            name='EdificioConsumo',
            fields=[
                ('consumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionCO2.Consumo')),
                ('tipo', models.CharField(choices=[(1, 'Agua'), (2, 'Electricidad'), (3, 'Aceite'), (4, 'Propano'), (5, 'Gas Natural')], max_length=50, verbose_name='¿Que ha consumido?')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Edificio')),
            ],
            bases=('GestionCO2.consumo',),
        ),
    ]
