# Generated by Django 3.0rc1 on 2019-11-22 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0010_auto_20191122_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('fecha_publicacion_mensaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('respondido', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCO2.Empresa')),
            ],
        ),
    ]
