# Generated by Django 2.2.7 on 2019-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0013_experto'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
