# Generated by Django 2.2.7 on 2019-12-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0015_auto_20191230_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='autorizado',
            field=models.IntegerField(default=0),
        ),
    ]
