# Generated by Django 3.0rc1 on 2020-01-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCO2', '0016_experto_autorizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
